### ISSUE TITLE
Actions.groovy: 132: The variable [jsonHash] is declared final but is reassigned

### ISSUE THREAD

**Issue by marielle-spiteri** [Bonitasoft-Community/page_gasolinetruck#1]
Hi, 

There seem to be a compatibility issue  with BonitaStudioCommunity-2021.2-u0, installing the page V1.10.0 in an application raises this error: 

03-Feb-2022 15:28:31.048 INFO [http-nio-8080-exec-7] java_util_logging_Logger$info.call #### ##############################CustomPage: return json[{"listevents":"<table><\/table>","listbdmavailable":[],"listcatalog":[],"datas":[],"status":"OK"}]
03-Feb-2022 15:28:31.900 WARNING [http-nio-8080-exec-6] org.bonitasoft.livingapps.LivingApplicationPageServlet.handleException Error while trying to render the application page custompage_gasolinetruck
	org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
file:/home/user/Documents/Studios/BonitaStudioCommunity-2021.2-u0/workspace/tomcat/server/temp/bonita_portal_40804@host/tenants/1/pages/custompage_gasolinetruck/Actions.groovy: 132: The variable [jsonHash] is declared final but is reassigned
. At [132:17]  @ line 132, column 17.
                   jsonHash = (Map<String, Object>) JSONValue.parse( paramJsonSt );
                   ^

1 error

		at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:295)
		at org.codehaus.groovy.control.CompilationUnit$IPrimaryClassNodeOperation.doPhaseOperation(CompilationUnit.java:984)
		at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:671)
		at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:635)
		at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:389)
		at groovy.lang.GroovyClassLoader.lambda$parseClass$3(GroovyClassLoader.java:332)
		at org.codehaus.groovy.runtime.memoize.StampedCommonCache.compute(StampedCommonCache.java:163)
		at org.codehaus.groovy.runtime.memoize.StampedCommonCache.getAndPut(StampedCommonCache.java:154)
		at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:330)
		at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:314)
		at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:244)
		at org.bonitasoft.console.common.server.page.CustomPageService.registerPage(CustomPageService.java:140)
		at org.bonitasoft.console.common.server.page.PageRenderer.displayGroovyPage(PageRenderer.java:138)
		at org.bonitasoft.console.common.server.page.PageRenderer.displayCustomPage(PageRenderer.java:95)
		at org.bonitasoft.console.common.server.page.PageRenderer.displayCustomPage(PageRenderer.java:61)
		at org.bonitasoft.livingapps.LivingApplicationPageServlet.doGet(LivingApplicationPageServlet.java:132)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
		at org.bonitasoft.livingapps.LivingApplicationPageServlet.service(LivingApplicationPageServlet.java:87)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
		at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
		at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
		at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:394)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.bonitasoft.console.common.server.filter.CacheFilter.excludePatternFiltering(CacheFilter.java:81)
		at org.bonitasoft.console.common.server.filter.ExcludingPatternFilter.doFilter(ExcludingPatternFilter.java:35)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.bonitasoft.console.common.server.login.filter.AuthenticationRule.proceedWithRequest(AuthenticationRule.java:53)
		at org.bonitasoft.console.common.server.login.filter.AuthenticationFilter.isAuthorized(AuthenticationFilter.java:132)
		at org.bonitasoft.console.common.server.login.filter.AuthenticationFilter.doAuthenticationFiltering(AuthenticationFilter.java:107)
		at org.bonitasoft.console.common.server.login.filter.AuthenticationFilter.proceedWithFiltering(AuthenticationFilter.java:94)
		at org.bonitasoft.console.common.server.filter.ExcludingPatternFilter.doFilter(ExcludingPatternFilter.java:37)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.bonitasoft.console.common.server.login.filter.AbstractAuthorizationFilter.doFilter(AbstractAuthorizationFilter.java:61)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.bonitasoft.console.common.server.login.filter.ContentTypeSecurityFilter.proceedWithFiltering(ContentTypeSecurityFilter.java:65)
		at org.bonitasoft.console.common.server.filter.ExcludingPatternFilter.doFilter(ExcludingPatternFilter.java:37)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.bonitasoft.console.common.server.filter.ExcludingPatternFilter.excludePatternFiltering(ExcludingPatternFilter.java:42)
		at org.bonitasoft.console.common.server.filter.ExcludingPatternFilter.doFilter(ExcludingPatternFilter.java:35)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1726)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:829)
03-Feb-2022 15:28:31.903 SEVERE [http-nio-8080-exec-6] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [livingApplicationPageServlet] in context with path [/bonita] threw exception
	java.lang.NullPointerException
		at org.codehaus.groovy.control.io.AbstractReaderSource.getLine(AbstractReaderSource.java:76)
		at org.codehaus.groovy.control.SourceUnit.getSample(SourceUnit.java:279)
		at org.codehaus.groovy.control.messages.SyntaxErrorMessage.write(SyntaxErrorMessage.java:54)
		at org.codehaus.groovy.control.ErrorCollector.write(ErrorCollector.java:306)
		at org.codehaus.groovy.control.ErrorCollector.write(ErrorCollector.java:326)
		at org.codehaus.groovy.control.MultipleCompilationErrorsException.getMessage(MultipleCompilationErrorsException.java:59)
		at org.bonitasoft.livingapps.LivingApplicationPageServlet.handleException(LivingApplicationPageServlet.java:234)
		at org.bonitasoft.livingapps.LivingApplicationPageServlet.doGet(LivingApplicationPageServlet.java:148)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
		at org.bonitasoft.livingapps.LivingApplicationPageServlet.service(LivingApplicationPageServlet.java:87)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
		at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
		at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
		at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:394)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.bonitasoft.console.common.server.filter.CacheFilter.excludePatternFiltering(CacheFilter.java:81)
		at org.bonitasoft.console.common.server.filter.ExcludingPatternFilter.doFilter(ExcludingPatternFilter.java:35)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.bonitasoft.console.common.server.login.filter.AuthenticationRule.proceedWithRequest(AuthenticationRule.java:53)
		at org.bonitasoft.console.common.server.login.filter.AuthenticationFilter.isAuthorized(AuthenticationFilter.java:132)
		at org.bonitasoft.console.common.server.login.filter.AuthenticationFilter.doAuthenticationFiltering(AuthenticationFilter.java:107)
		at org.bonitasoft.console.common.server.login.filter.AuthenticationFilter.proceedWithFiltering(AuthenticationFilter.java:94)
		at org.bonitasoft.console.common.server.filter.ExcludingPatternFilter.doFilter(ExcludingPatternFilter.java:37)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.bonitasoft.console.common.server.login.filter.AbstractAuthorizationFilter.doFilter(AbstractAuthorizationFilter.java:61)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.bonitasoft.console.common.server.login.filter.ContentTypeSecurityFilter.proceedWithFiltering(ContentTypeSecurityFilter.java:65)
		at org.bonitasoft.console.common.server.filter.ExcludingPatternFilter.doFilter(ExcludingPatternFilter.java:37)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.bonitasoft.console.common.server.filter.ExcludingPatternFilter.excludePatternFiltering(ExcludingPatternFilter.java:42)
		at org.bonitasoft.console.common.server.filter.ExcludingPatternFilter.doFilter(ExcludingPatternFilter.java:35)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1726)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:829)

See here: 
https://community.bonitasoft.com/questions-and-answers/trying-install-gasoline-project-community-20212

**Comment by PierrickVoulet** [comment]
This was fixed in release1.10 (see https://github.com/Bonitasoft-Community/page_gasolinetruck/commit/2eb95c8e60b2c8f72621d0d93b95b0ee994ba24d)
